version: "3.7"

services:
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    ports:
      - 27017:27017
    volumes:
      - mongodb-data:/data/db
    networks:
      - frequenz_net

  frequenzdieb-api:
    image: ch.frequenzdieb/frequenzdieb-rest-api:latest
    environment:
      - FREQUENZDIEB_MAIL_PSW=${FREQUENZDIEB_MAIL_PSW}
      - FREQUENZDIEB_MAIL_USER=${FREQUENZDIEB_MAIL_USER}
      - FREQUENZDIEB_MAIL_SENDER=${FREQUENZDIEB_MAIL_SENDER}
      - FREQUENZDIEB_MAIL_HOST=${FREQUENZDIEB_MAIL_HOST}
    ports:
      - 8080:8080
    expose:
      - 8080
    logging:
      driver: json-file
    networks:
      - frequenz_net
    depends_on:
      - mongodb

networks:
  frequenz_net: {}

volumes:
  mongodb-data:
