/**
 * Frequenzdieb REST-API
 * REST-API for the frequenzdieb.ch homepage
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: band@frequenzdieb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TicketType {
  readonly id?: string
  readonly createdDate?: number
  readonly lastModifiedDate?: number
  name: string
  attributeIds?: Array<string>
  validationRules?: Array<string>
}
