/**
 * Frequenzdieb REST-API
 * REST-API for the frequenzdieb.ch homepage
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: band@frequenzdieb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface TicketAttribute {
  readonly id?: string
  readonly createdDate?: number
  readonly lastModifiedDate?: number
  key: string
  value: string
  text?: string
  tag?: string
  archived?: boolean
  readonly validationRules?: Array<string>
}
