/**
 * Frequenzdieb REST-API
 * REST-API for the frequenzdieb.ch homepage
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: band@frequenzdieb.ch
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ValidationErrorDetails } from './validationErrorDetails'

export interface ValidationError {
  code: string
  details?: { [key: string]: ValidationErrorDetails }
  value?: object
  nested?: Array<ValidationError>
}
