/**
 * Frequenzdieb REST-API
 * REST-API for the frequenzdieb.ch homepage
 *
 * OpenAPI spec version: 0.0.1
 * Contact: band@frequenzdieb.ch
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface InlineResponse204 {
  /**
   * the qr-code as base64/png image
   */
  qrcode?: string
}
